import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const qml = fs.readFileSync(new URL('../Service.qml', import.meta.url), 'utf8');
const fn = qml.match(/  function renameCity\([\s\S]*?\n  \}/)[0];
let saves = [];
const root = { initialized: true, cityName: 'Omaville' };
const rename = vm.runInNewContext('(' + fn + ')', { root, flushState() { saves.push(root.cityName); } });
assert.equal(rename('  New\n  Haven  '), true);
assert.equal(root.cityName, 'New Haven');
assert.deepEqual(saves, ['New Haven']);
assert.equal(rename('New Haven'), true);
assert.equal(saves.length, 1);
for (const invalid of ['', '  ', '\n\t', 'x'.repeat(41)]) assert.equal(rename(invalid), false);
assert.equal(root.cityName, 'New Haven');
assert.equal(rename('São Tomé'), true);
assert.equal(rename('x'.repeat(40)), true);
root.initialized = false;
assert.equal(rename('Not loaded yet'), false);
assert.equal(saves.length, 3);
console.log('PASS: town name normalization, empty/length validation, Unicode, unchanged names, save dispatch, and initialization guard.');
